version: '3.5'
services:
  extranet-test:
    container_name: extranet_test
    image: weboaks/node-karma-protractor-chrome:debian-node16
    volumes:
      - .:/app
    working_dir: /app
    command: yarn test -- --browsers=ChromeHeadlessNoSandbox --watch=false
